language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - chmod +x init.sh
  - ./init.sh
install:
  - cd pcp && npm install ; cd ..
  - cd http && npm install ; cd ..
script:
  - cd pcp && grunt release-build ; cd ..
  - cd http && grunt release-build ; cd ..
